title: Nordic Websolutions
description: Aus dem Alltag der Softwareentwicklung
url: "https://nordicwebsolutions.de"
baseurl: ""

# Theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Navigation
header_pages:
  - about.md
  - posts.md

# Markdown processor
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/
